[project]
site_name = "Manabiya"
site_description = "Manabiya SASU."
site_author = "Dimitar Dimitrov (drdv.net)"
site_url = "https://manabiya.fr/"
copyright = """&copy; 2025-2026 Manabiya"""

nav = [
  { "Home" = "index.md" },
  { "Courses" = [
      "courses/index.md",
	  { "Introduction to Python" = "courses/python-intro-data-science.md" },
	  { "Git for non-coders" = "courses/git.md" },
  ]},
  { "Events & Workshops" = "workshops.md" },
  { "FAQ" = "faq.md" },
  { "Contact" = "contact.md" }
]

# ----------------------------------------------------------------------------
# Section for configuring theme options
# ----------------------------------------------------------------------------
[project.theme]
language = "en"
favicon = "img/logo-manabiya.png"
logo = "img/logo-manabiya.png"

features = [
    "content.code.annotate",
    "content.code.copy",
    "content.code.select",
    "content.footnote.tooltips",
    "content.tooltips",
    "header.autohide",
    "navigation.tabs",
    "navigation.tracking",
    "search.highlight",
]

[[project.theme.palette]]
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"
logo = "fontawesome/solid/lines-leaning"
favicon = "fontawesome/solid/lines-leaning"


[[project.theme.palette]]
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "Switch to light mode"

[project.extra]
generator = false

[[project.extra.social]]
icon = "fontawesome/solid/at"
link = "mailto:contact@manabiya.fr"
